CREATE DATABASE yelp_us_out;

CREATE TABLE group(
	GroupId INT NOT NULL AUTO_INCREMENT,
	GroupName VARCHAR(50) NOT NULL,
	MemberCount INT DEFAULT 0,
	CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP, 
	UpdateDate DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY(GroupId)
);

CREATE TABLE group_details(
	GroupId INT NOT NULL,
	Latitude INT NOT NULL,
	Longitude INT NOT NULL,
	Radius INT DEFAULT NULL,
	Price VARCHAR(20) DEFAULT NULL,
	OpenAt INT DEFAULT NULL,
	Categories VARCHAR(512) DEFAULT NULL
);


