CREATE DATABASE yelp_us_out;

CREATE TABLE group(
	group_id INT NOT NULL AUTO_INCREMENT,
	group_name VARCHAR(50) NOT NULL,
	member_count INT DEFAULT 0,
	create_date DATETIME DEFAULT CURRENT_TIMESTAMP, 
	update_date DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY(GroupId)
);

CREATE TABLE group_details(
	group_id INT NOT NULL,
	latitude INT NOT NULL,
	longitude INT NOT NULL,
	radius INT DEFAULT NULL,
	price VARCHAR(20) DEFAULT NULL,
	open_at INT DEFAULT NULL,
	categories VARCHAR(512) DEFAULT NULL
);


